export type { DialogDescriptionProps } from "./dialog-description";
export type { DialogOverlayProps } from "./dialog-overlay";
export type { DialogContentProps } from "./dialog-content";
export type { DialogTriggerProps } from "./dialog-trigger";
export type { DialogHeaderProps } from "./dialog-header";
export type { DialogFooterProps } from "./dialog-footer";
export { DialogDescription } from "./dialog-description";
export type { DialogTitleProps } from "./dialog-title";
export type { DialogCloseProps } from "./dialog-close";
export type { DialogBodyProps } from "./dialog-body";

export type { DialogRootProps } from "./dialog-root";
export { DialogOverlay } from "./dialog-overlay";
export { DialogContent } from "./dialog-content";
export { DialogTrigger } from "./dialog-trigger";
export { DialogHeader } from "./dialog-header";
export { DialogFooter } from "./dialog-footer";
export { DialogTitle } from "./dialog-title";
export { DialogClose } from "./dialog-close";
export { DialogBody } from "./dialog-body";
export { DialogRoot } from "./dialog-root";
